nginx:
    container_name: nginx
    build: ./nginx
    links:
        - node1:node1
        - node2:node2
    ports:
        - "8000:80"
node1:
    container_name: node1
    build: ./node
    links:
        - redis
    ports:
        - "8080"
node2:
    container_name: node2
    build: ./node
    links:
        - redis
    ports:
        - "8080"
redis:
    container_name: redis
    image: redis
    ports:
        - "6379"
