##################### 
# Nginx Dockerfile  #
#####################

# Set nginx base image
FROM nginx 

#Set maintainer
MAINTAINER Toon Lamberigts

#Pre-reqs 
# RUN

# App installation
# RUN


# Copy custom config file for nginx
# COPY FROM (host) TO (container) (kan path instellen, moet niet huidige dir zijn)
COPY nginx.conf /etc/nginx/nginx.conf

# Expose necessary ports
# Allow access to this container on port 80
EXPOSE 80





